name: Test with tox

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    types: ["opened", "reopened"]
  tags: ["*.*.*"]

jobs:
  run-tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["{{ '", "'.join(cookiecutter.target_versions.split(" ")) }}"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox